-- Baseline schema for the Thesis Management System: everything the database had at version 4.
--
-- Do not edit this file. It has already run on real databases, and changing it would make them
-- disagree about their shape. To change the schema, add the next numbered file in this folder,
-- for example 005_add_notifications.sql.
--
-- It is numbered 004 because databases built before migrations existed already report
-- user_version = 4, so they skip this file and keep their data.

CREATE TABLE IF NOT EXISTS users (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  name          TEXT    NOT NULL,
  email         TEXT    NOT NULL UNIQUE COLLATE NOCASE,
  password_hash TEXT    NOT NULL,
  role          TEXT    NOT NULL CHECK (role IN ('student', 'adviser', 'admin')),
  program       TEXT    NOT NULL DEFAULT '',  -- degree program (students) or department (advisers)
  is_active     INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- A thesis written by a group of students (see thesis_members); the adviser is assigned by an admin
CREATE TABLE IF NOT EXISTS theses (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  adviser_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  title      TEXT    NOT NULL,
  abstract   TEXT    NOT NULL DEFAULT '',
  keywords   TEXT    NOT NULL DEFAULT '',
  status     TEXT    NOT NULL DEFAULT 'draft'
             CHECK (status IN ('draft', 'under_review', 'revisions_required', 'in_progress', 'completed')),
  created_at TEXT    NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- Students in a thesis group. A student belongs to at most one thesis, and each group has one leader.
CREATE TABLE IF NOT EXISTS thesis_members (
  thesis_id  INTEGER NOT NULL REFERENCES theses(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  is_leader  INTEGER NOT NULL DEFAULT 0 CHECK (is_leader IN (0, 1)),
  joined_at  TEXT    NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (thesis_id, student_id)
);

-- A manuscript uploaded for one stage of the thesis. Its status comes from its review.
CREATE TABLE IF NOT EXISTS submissions (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  thesis_id    INTEGER NOT NULL REFERENCES theses(id) ON DELETE CASCADE,
  stage        TEXT    NOT NULL CHECK (stage IN ('proposal', 'chapters_1_3', 'chapters_4_5', 'final')),
  notes        TEXT    NOT NULL DEFAULT '',
  file_name    TEXT,
  stored_name  TEXT,
  file_size    INTEGER,
  mime_type    TEXT,
  submitted_at TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- The adviser's decision on a submission (at most one per submission)
CREATE TABLE IF NOT EXISTS reviews (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  submission_id INTEGER NOT NULL UNIQUE REFERENCES submissions(id) ON DELETE CASCADE,
  reviewer_id   INTEGER REFERENCES users(id) ON DELETE SET NULL,
  decision      TEXT    NOT NULL CHECK (decision IN ('approved', 'revisions_requested')),
  feedback      TEXT    NOT NULL DEFAULT '',
  created_at    TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- Discussion between the student and adviser on a submission
CREATE TABLE IF NOT EXISTS comments (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  submission_id INTEGER NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
  author_id     INTEGER REFERENCES users(id) ON DELETE SET NULL,
  body          TEXT    NOT NULL,
  created_at    TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- Consultations and defenses for a thesis
CREATE TABLE IF NOT EXISTS schedules (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  thesis_id        INTEGER NOT NULL REFERENCES theses(id) ON DELETE CASCADE,
  type             TEXT    NOT NULL CHECK (type IN ('consultation', 'proposal_defense', 'final_defense')),
  title            TEXT    NOT NULL,
  starts_at        TEXT    NOT NULL,  -- UTC, 'YYYY-MM-DD HH:MM:SS'
  duration_minutes INTEGER NOT NULL CHECK (duration_minutes BETWEEN 15 AND 480),
  mode             TEXT    NOT NULL CHECK (mode IN ('in_person', 'online')),
  location         TEXT    NOT NULL DEFAULT '',  -- room or meeting link
  notes            TEXT    NOT NULL DEFAULT '',
  status           TEXT    NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed', 'cancelled')),
  created_by       INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at       TEXT    NOT NULL DEFAULT (datetime('now')),
  updated_at       TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- Advisers sitting on a defense panel (many-to-many between schedules and users)
CREATE TABLE IF NOT EXISTS schedule_panelists (
  schedule_id INTEGER NOT NULL REFERENCES schedules(id) ON DELETE CASCADE,
  adviser_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (schedule_id, adviser_id)
);

CREATE TABLE IF NOT EXISTS activity (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  thesis_id  INTEGER NOT NULL REFERENCES theses(id) ON DELETE CASCADE,
  actor_id   INTEGER REFERENCES users(id) ON DELETE SET NULL,
  action     TEXT    NOT NULL,
  created_at TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- One-time password reset links. Only a SHA-256 hash of the token is stored.
CREATE TABLE IF NOT EXISTS password_resets (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT    NOT NULL UNIQUE,
  expires_at TEXT    NOT NULL,  -- UTC, 'YYYY-MM-DD HH:MM:SS'
  created_at TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- Submissions joined with their review; status is 'pending' until a review exists
CREATE VIEW IF NOT EXISTS submission_details AS
  SELECT s.*,
    COALESCE(r.decision, 'pending') AS status,
    r.reviewer_id,
    r.feedback   AS review_feedback,
    r.created_at AS reviewed_at
  FROM submissions s
  LEFT JOIN reviews r ON r.submission_id = s.id;

CREATE INDEX IF NOT EXISTS idx_theses_adviser       ON theses(adviser_id);
CREATE INDEX IF NOT EXISTS idx_submissions_thesis   ON submissions(thesis_id);
CREATE INDEX IF NOT EXISTS idx_comments_submission  ON comments(submission_id);
CREATE INDEX IF NOT EXISTS idx_schedules_thesis     ON schedules(thesis_id);
CREATE INDEX IF NOT EXISTS idx_schedules_starts_at  ON schedules(starts_at);
CREATE INDEX IF NOT EXISTS idx_panelists_adviser    ON schedule_panelists(adviser_id);
CREATE INDEX IF NOT EXISTS idx_activity_thesis      ON activity(thesis_id);
CREATE INDEX IF NOT EXISTS idx_password_resets_user ON password_resets(user_id);
-- At most one leader per group
CREATE UNIQUE INDEX IF NOT EXISTS idx_members_one_leader ON thesis_members(thesis_id) WHERE is_leader = 1;
