import fs from 'node:fs';
import path from 'node:path';
import config from '../config/index.js';

export function storedFilePath(storedName) {
  // Stored names are generated by the server, but strip any directory parts to be safe
  return path.join(config.uploadDir, path.basename(storedName));
}

export function deleteStoredFiles(storedNames) {
  for (const name of storedNames) {
    if (name) fs.rmSync(storedFilePath(name), { force: true });
  }
}
